### ISSUE TITLE
Key Presses do not work during BIOS. No Special keys working. Input Lag.

### ISSUE THREAD

**Issue by Spamm00r** [mtlynch/key-mime-pi#22]
Hi,

I tested this on my Zero WH and it works good on Windows. But I have the following issues with it.

1. The Key passthrough does not work while the server is in BIOS. I have ensured that the ZeroWH has a external Power Supply, that is independent of the Servers Power State. The WebUI shows me that I'm connected, but any keypress is not passed through, as long as the server that I want to control is in BIOS stage. Also the command window of the Zero WH does not show any movement while the Server is in BIOS stage. Once the server is booted up and in Windows, key Passthrough starts working again and the command window will show keypresses transfered.

2. You can not passthrough special key kombinations like CTRL+ALT+DEL. Instead it will be executed on the client computer. Im some scenarios it will be necessary to execute special key combinations.

3. The keypresses sometimes have a noticeable lag after a while. The lag becomes so long that sometimes I think the connection has dropped, but eventually the key presses will be passed through all at once.

Unfortunately the key use scenario for me is to be able to pass through keys to the server while in BIOS or preboot phase or while WIndows or any other OS is not fully loaded yet, or no Network connection is available, at which stage one could use any other remote control solution.

With no Keypassthrough at BIOS stage, this application has limited use.

I think you have to change the keyboard emulation type to be able to also use the keypassthrough at BIOS level. But I have too limited knowledge about that.

**Comment by mtlynch** [comment]
Thanks for filing these, @Spamm00r.

key-mime-pi was basically a prototype for [tinypilot](https://github.com/mtlynch/tinypilot), so I'll accept PRs for key-mime-pi, but I'm focusing development on TinyPilot. TinyPilot does everything key-mime-pi does and adds video capture, but it still works even without video capture.

>The Key passthrough does not work while the server is in BIOS. I have ensured that the ZeroWH has a external Power Supply, that is independent of the Servers Power State. The WebUI shows me that I'm connected, but any keypress is not passed through, as long as the server that I want to control is in BIOS stage. Also the command window of the Zero WH does not show any movement while the Server is in BIOS stage. Once the server is booted up and in Windows, key Passthrough starts working again and the command window will show keypresses transfered.

I've seen this in my tests, but my experience is that it won't work if you press the button before the machine has reached the stage of accepting keyboard input. key-mime-pi has a bug where it will hang while waiting for a machine to accept keyboard input, but this has been [fixed](https://github.com/mtlynch/tinypilot/issues/47) in TinyPilot.

>You can not passthrough special key kombinations like CTRL+ALT+DEL. Instead it will be executed on the client computer. Im some scenarios it will be necessary to execute special key combinations.

This is supported in TinyPilot. It allows you to simulate modifier keys to hold down even if you're not holding them down on the client computer. So you'd enable "Ctrl" and "Alt" in the Web UI and then push "Del" on the client computer, and TinyPilot will send a Ctrl+Alt+Del to the target computer.

>The keypresses sometimes have a noticeable lag after a while. The lag becomes so long that sometimes I think the connection has dropped, but eventually the key presses will be passed through all at once.

This might be the same hanging issue. Can you try it with TinyPilot and see if the behavior is the same?

Also, a meta-note, I can address your issues faster and allow you to track them more easily if you use a separate bug for a separate issue. This is one bug but it contains three separate issues..
